In [1]:
import numpy as np

In [2]:
# dtype -> data type: kiểu dữ liệu
arr = np.array([1, 2, 3, 4], dtype=int)
print(arr.dtype)

int32


In [3]:
arr1 = np.array([1, 2, 3, 4.])
print(arr1.dtype)

float64


In [4]:
# Khởi toạ mảng 2 chiều
arr_d2 = np.array([(1, 2, 3),
                  (3, 4, 5)], dtype = int)
print(arr_d2)
print(arr_d2.dtype)
print(arr_d2.ndim)

[[1 2 3]
 [3 4 5]]
int32
2


In [5]:
# Khởi tạo mảng 3 chiều
arr_d3 = np.array(([(1, 1, 1), (1, 1, 1)],
                   [(2, 2, 2), (2, 2, 2)],
                   [(3, 3, 3), (3, 3, 3)]), dtype=int)
print(arr_d3.shape)
(arr_d3[1]).ndim

(3, 2, 3)


2

In [6]:
arr_one_3d = np.ones([2, 3, 4], dtype=float)
print(arr_one_3d)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [7]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [8]:
np.random.random((2,3))

array([[0.69903148, 0.38775682, 0.1777322 ],
       [0.98016849, 0.98709235, 0.47940239]])

In [9]:
# Khởi tạo ma trận đơn vị từ 
# eye -> identiny matrix : ma trận đơn vị
np.eye(5, dtype=bool)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [10]:
# Khởi tạo mà trận đường chéo vơi đương chéo cho trước
# diag -> 'diagonel': đường chéo

np.diag((1, 2, 3, 4))


array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [11]:
# Tạo mảng với giá trị không được định sẵn
# empty: trống
np.empty((3,3), dtype=int)

array([[  0,   1,   0],
       [500, 728,   0],
       [768,   0,   0]])

In [12]:
# Tạo mẳng từ một list hoặc tupe
# list: danh sách
# tupe: tập hợp chú ý tupe là kiểu immutable(bất biến) 
tp = ((1, 2, 3), (3, 4, 5))
lst = [[1, 2, 3], [3, 4, 'a']]
print(np.array(tp), '\n')
print(np.asarray(lst))
print(np.asarray(lst).dtype)

[[1 2 3]
 [3 4 5]] 

[['1' '2' '3']
 ['3' '4' 'a']]
<U11


In [13]:
# Tạo mảng từ các hàm sao chép shape
t3 = np.array([[6, 2], [2, 4]])
print(t3)
print(t3.shape)
print(np.empty_like(t3))

[[6 2]
 [2 4]]
(2, 2)
[[0 0]
 [0 0]]


In [14]:
np.ones_like(t3)

array([[1, 1],
       [1, 1]])

In [15]:
np.zeros_like(t3)

array([[0, 0],
       [0, 0]])

In [16]:
np.full_like(t3, fill_value=0.1, dtype=int)

array([[0, 0],
       [0, 0]])

In [17]:
np.full_like(t3, fill_value=0.1, dtype=float)

array([[0.1, 0.1],
       [0.1, 0.1]])

Các thuộc tính cơ bản của mảng

In [18]:
x = np.zeros((2, 3), dtype=float)

print("Kiểu dữ liệu của phần tử trong mảng:", x.dtype)
print("Kích thước của mảng:", x.shape)
print("Số phần tử trong mảng:", x.size)
print("Số chiều của mảng:", x.ndim) # number of dimetion

Kiểu dữ liệu của phần tử trong mảng: float64
Kích thước của mảng: (2, 3)
Số phần tử trong mảng: 6
Số chiều của mảng: 2


In [19]:
arr = np.array(['apple', 'bananaaaaaa', 'cherry'])
print(arr.dtype)

<U11


In [20]:
arr = np.array([1, 256, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'256' b'3' b'4']
|S3


Chuyển đổi kiểu dữ liệu của mảng

In [21]:
arr = np.array([1.1, 2.1, 3.1, 0.0, 0])
t1 = arr.astype('i')
t2 = arr.astype(int)
t3 = arr.astype(float)
t4 = arr.astype(bool)

print(t1)
print(t1.dtype)
print(t2)
print(t2.dtype)
print(t3)
print(t3.dtype)
print(t4)
print(t4.dtype)

[1 2 3 0 0]
int32
[1 2 3 0 0]
int32
[1.1 2.1 3.1 0.  0. ]
float64
[ True  True  True False False]
bool


In [22]:
## Tạo một mảng có 5 kích thước bằng cách sử dụng ndmin bằng cách sử dụng một vectơ có các giá trị 1,2,3,4
## và xác minh rằng chiều cuối cùng có giá trị 4:
arr = np.array([1, 2, 3, 4], ndmin=3)

print(arr)
print('shape of array :', arr.shape)
print(arr.size)

[[[1 2 3 4]]]
shape of array : (1, 1, 4)
4


In [23]:
t = np.array((1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12))
# Khởi tạo ma trận với range()
t1 = np.array(range(1, 11), dtype=int)
print(t)
print(t.shape)
print(t1)
print(t1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [24]:
# reshape() from 1D to 2D
print(t1.reshape(5, 2))
print(t1.reshape(2, 5))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [25]:
# reshap() from 2D to 3D
print(t.reshape(2, 3, 2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [26]:
# làm phẳng mảng
t = np.array([[1, 2, 3], [4, 5, 6]])

t1 = t.reshape(-1)
print(t1)
print(t.flatten())

[1 2 3 4 5 6]
[1 2 3 4 5 6]
